services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    Disjfa\TimetableBundle\:
        resource: './../../*'
        exclude: './../../{Entity,Migrations,Tests}'

    Disjfa\TimetableBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Disjfa\TimetableBundle\Security\:
        resource: './../../Security/*'
        tags: ['security.voter']
